<a href="https://colab.research.google.com/github/ritsdavande/Barber_appointment_system/blob/main/numpy_library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [255]:
import numpy as np

array=[1,2,3,4]
np.array

In [256]:
array = [1, 2, 3, 4]
print(np.array(array))

[1 2 3 4]


In [257]:
np.array(([1,2,3],[3,4,5]))

array([[1, 2, 3],
       [3, 4, 5]])

In [258]:
arr_5d = np.array([[[[[[1, 2], [3, 4],[5,6],[7,8]]]]],
                  [[[[[1, 2], [3, 4],[5,6],[7,8]]]]]])
print(arr_5d)
print(type(arr_5d))
print(arr_5d.shape)

[[[[[[1 2]
     [3 4]
     [5 6]
     [7 8]]]]]




 [[[[[1 2]
     [3 4]
     [5 6]
     [7 8]]]]]]
<class 'numpy.ndarray'>
(2, 1, 1, 1, 4, 2)


In [259]:
a=np.array([[[1,2],[3,4],[5,6]]])
print(a.ndim)
print(type(a))
print(a.shape)
a

3
<class 'numpy.ndarray'>
(1, 3, 2)


array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [260]:
arr=np.zeros((5))
print(arr)
a=np.zeros((4,3,2))
a
b=np.random.randint((4))
print(b)

[0. 0. 0. 0. 0.]
0


In [261]:
b=np.random.rand(2,3)
print(b)

[[0.12368242 0.75869342 0.40253276]
 [0.71089091 0.82105494 0.82675039]]


In [262]:
arr=np.ones((2,1,2,3))
print(arr)
arr.ndim

[[[[1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]]]]


4

In [263]:
a=np.zeros((0,0))
print(a.ndim)
a

2


array([], shape=(0, 0), dtype=float64)

In [264]:
a=np.full((7,7),7)
a

array([[7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7]])

In [265]:
arr=np.eye(2)
arr

array([[1., 0.],
       [0., 1.]])

In [266]:
a=np.square(2)
a

np.int64(4)

In [267]:
a=[1,2,5]
a=np.square(a)
a

array([ 1,  4, 25])

In [268]:
x=10
x

10

In [269]:
a=np.random.random((1,1,1,1))
a

array([[[[0.32250437]]]])

In [270]:
a=np.empty([2,2],dtype='int64')
a

array([[4607182418800017408,                   0],
       [                  0, 4607182418800017408]])

In [271]:
a=np.empty_like([2,3])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[4607182418800017408 4607182418800017408]


In [272]:
a=np.empty([2,3])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[[0.21070741 0.49194788 0.0916866 ]
 [0.83596071 0.9865562  0.64524881]]


In [273]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [275]:
a=np.arange(4,10,2)
a

array([4, 6, 8])

In [277]:
a=np.linspace(0,10,num=10)
a

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [278]:
arr=np.array([[[3,4,5],[2,8,7]],[[5,8,7],[5,4,9]]])
print(arr[0])
print(arr[0,1])

[[3 4 5]
 [2 8 7]]
[2 8 7]


In [284]:
arr=np.array([[3,4,5],[2,8,7],[5,8,7],[5,4,9]])
b=np.array((0,2,0,1))
arr[np.arange(4),b]+=10 #[0,1,2,3]
print(arr)

[[13  4  5]
 [ 2  8 17]
 [15  8  7]
 [ 5 14  9]]


In [286]:
a=np.array([[1,2,3],[13,4,5]])
b=np.nonzero(a>5)
print(b)#return array where finding indices where elements are less thann 5

(array([1]), array([0]))


In [289]:
a=np.array([[[3,4],[5,6]]])
a[0,0]=10
a

array([[[10, 10],
        [ 5,  6]]])

In [290]:
#Broadcasting
a=np.array([[[2,3],[4,5]]])#shape (1,2,2)
b=np.array([[[6,7],[8,9]]])#shape (2,2)
print(a+b)
print(np.add(a,b))

[[[ 8 10]
  [12 14]]]
[[[ 8 10]
  [12 14]]]


In [291]:
#Scalar Broadcasting
data=np.array([1.0,2.0])
print(data*1.6)

[1.6 3.2]


In [292]:
#Sqrt
a=np.sqrt([[2,3]])
print(a)

[[1.41421356 1.73205081]]


In [293]:
a=np.array([[2,3],[4,5]])
b=a.flatten()
b

array([2, 3, 4, 5])

In [294]:
a=np.array([[2,3],[4,5]])
b=np.array([[12,13],[45,55]])
c=np.concatenate((a,b),axis=1)
c

array([[ 2,  3, 12, 13],
       [ 4,  5, 45, 55]])

In [296]:
a=np.array([1,2,3,5],dtype='i')
a

array([1, 2, 3, 5], dtype=int32)

In [298]:
a=np.array([1,2,5,3,5])
print(np.unique(a))

[1 2 3 5]
